# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazydbx" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "3e43ef2d0e7f928e758916146226240a043897b26ceb9f707c101257aa43765a"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa2dab84a5a93cb6af35f69f7b194daf4f79ee95692adae2148af8c84b94e937"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5ce1035c92829f4e9878c82ec350b7f3daabca1c6653e2363b7c413ad31bc2c3"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "75e387932e07deeb614fed98d3aa2daafcceedac90252599b91ac058a2e4f28c"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lazydbx"
  desc "A lazier way to Databricks — a fast, colorful terminal UI"
  homepage "https://github.com/jongracecox/lazydbx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazydbx"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazydbx"]
    end
  end

  # No zap stanza required
end
