# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazydbx" do
  version "0.6.2"

  on_macos do
    on_arm do
      sha256 "3087982058ff28af3021d49ab6a9ba724fdd27e630c056ebcbe2d9371ef7523b"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e2916d3daca6626efd040e7fa88662d3d1472c15c4c253529d9f14a0daf1ee1"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5035c7ae07f273b22d8bf734b1ef711b0896b61bf4619044e4e991308f161be4"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2e278df415e2cd047b5e5f39d88ab57ff9374d62574029c480dd0d1b16f0316"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lazydbx"
  desc "A lazier way to Databricks — a fast, colorful terminal UI"
  homepage "https://github.com/jongracecox/lazydbx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazydbx"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazydbx"]
    end
  end

  # No zap stanza required
end
