# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazydbx" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "ebb84ab6cc7ba1a18e3be153c58bdfb8b02e9866e4ff27c4f2429fc262fddd94"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b1c03771d6d0bf22be6179e0af17e9f9a4ef99638e453fa06bbfc93cc1cbf46"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f58b273f44cfa86f58ffb2538c57ccdd4cdd13c06193161b02996433070c498c"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab44c2917e6ddca12051f98e0fe5e4f38273fae1a5d664dfdc278b1400273c1f"
      url "https://github.com/jongracecox/lazydbx/releases/download/v#{version}/lazydbx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lazydbx"
  desc "A lazier way to Databricks — a fast, colorful terminal UI"
  homepage "https://github.com/jongracecox/lazydbx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazydbx"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazydbx"]
    end
  end

  # No zap stanza required

end
